In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [10]:
df_canada = pd.read_csv("../Dataset/IRCC_FF_TR_2017_05_CSV.csv", encoding="ISO-8859-1")
df_canada

,Unnamed: 0,Unnamed: 1,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Philippines,Philippines,46972,51292,44840,41762,40744,43689,39925,23642,14718,11901
1,India,Inde,8332,8341,7519,5974,6698,8033,6251,3335,3288,5749
2,Guatemala,Guatemala,1113,1239,1471,1520,1998,2488,2725,3140,4278,5603
3,Mexico,Mexique,4792,4449,2787,4080,3003,4245,3879,2493,7961,2574
4,"Korea, Republic of","Corée, République de",3469,3694,2720,2204,2485,3334,2561,1412,1415,2158
5,United States of America,États-Unis d'Amérique,6241,6182,5019,4937,5755,5875,4481,3216,1918,1584
6,France,France,2824,3098,3152,2981,3086,3312,3249,2502,1938,1424
7,United Kingdom and Overseas Territories,Royaume-Uni et territoires doutre mer,5796,5656,4198,3792,4070,4969,3889,2465,1597,1228
8,Thailand,Thaïlande,864,993,1234,1161,1404,1625,1541,997,946,1171
9,"China, People's Republic of","Chine, République populaire de",2724,2235,1716,1637,1668,1755,1397,907,938,1037
10,Jamaica,Jamaïque,1116,1117,1123,1239,1412,2255,2464,1474,1331,846
11,Italy,Italie,454,473,408,403,585,942,962,744,670,824
12,Japan,Japon,2029,1821,1243,782,839,1106,906,484,389,616
13,Ukraine,Ukraine,1087,1099,720,673,768,1173,1181,814,584,593
14,Brazil,Brésil,975,948,971,405,384,437,386,277,339,532
15,Portugal,Portugal,753,602,378,386,906,1383,1092,603,497,514
16,Israel,Israël,923,935,703,650,778,1072,885,550,351,382
17,Poland,Pologne,1059,764,386,381,749,1262,1142,658,394,374
18,Germany,Allemagne,2752,2366,1392,1147,1076,1161,870,515,386,370
19,"Ireland, Republic of","Irlande, République d'",535,583,543,517,1245,2095,1552,785,478,359
20,Honduras,Honduras,227,322,138,318,427,468,391,389,352,352
21,Australia,Australie,1244,1068,788,664,652,721,597,419,357,341
22,Spain,Espagne,233,254,236,222,396,593,595,427,295,296
23,"South Africa, Republic of","Afrique du Sud, République d'",985,933,826,693,639,628,532,362,276,251
24,Croatia,Croatie,88,86,44,68,168,604,786,564,308,199
25,Vietnam,Vietnam,230,182,124,90,157,185,158,78,73,192
26,Greece,Grèce,84,94,61,61,156,281,308,168,130,172
27,Nepal,Népal,246,260,225,209,247,416,568,413,217,171
28,Romania,Roumanie,1001,814,449,472,469,625,498,261,178,169
29,Belgium,Belgique,190,236,219,204,211,280,241,183,215,162
30,"Netherlands, The","Pays-Bas, Les",478,501,380,335,362,395,337,267,258,161
31,Hungary,Hongrie,159,201,183,219,255,368,397,269,162,152
32,Russia,Russie,518,415,330,256,241,293,264,192,136,148
33,"Serbia, Republic of","Serbie, République de",144,177,127,126,147,296,316,203,121,138
34,"Indonesia, Republic of","Indonésie, République d'",165,184,173,195,276,395,382,211,167,137
35,Norway,Norvège,117,122,73,72,97,143,188,146,134,132
36,Taiwan,Taïwan,168,345,411,147,159,267,247,111,94,127
37,Pakistan,Pakistan,284,270,200,194,215,337,319,169,149,126
38,Czech Republic,"Tchèque, République",109,106,85,85,146,271,272,133,113,111
39,New Zealand,Nouvelle-Zélande,544,519,427,421,370,419,329,262,163,108
40,Nicaragua,Nicaragua,65,67,29,54,58,69,86,53,72,107
41,Turkey,Turquie,239,198,152,139,120,150,120,64,71,103
42,Sweden,Suède,169,158,132,124,126,136,105,104,92,92
43,Sri Lanka,Sri Lanka,642,582,437,397,370,465,341,154,93,84
44,Iran,Iran,93,111,82,72,79,90,58,44,60,83
45,Colombia,Colombie,876,656,362,203,165,193,137,77,72,81
46,Peru,Pérou,305,306,245,211,247,236,196,121,88,80
47,Argentina,Argentine,161,122,93,77,83,86,79,56,67,79
48,Chile,Chili,406,313,148,126,136,194,174,89,52,78
49,"Trinidad and Tobago, Republic of","Trinité-et-Tobago, République de",197,205,117,107,105,146,58,48,43,76

In [14]:
#clean
# del df_canada["Unnamed: 0"]

In [25]:
df_canada = df_canada.rename(columns={'Unnamed: 1': "Country"})
df_canada
value = 0
for x in range(2008,2017):
 value = value + df_canada[x]
df_canada["Mean"] = x

KeyError: 2008

In [19]:
df_canada.head()

,Country,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,Mean
0,Philippines,46972,51292,44840,41762,40744,43689,39925,23642,14718,11901,98264
1,Inde,8332,8341,7519,5974,6698,8033,6251,3335,3288,5749,16673
2,Guatemala,1113,1239,1471,1520,1998,2488,2725,3140,4278,5603,2352
3,Mexique,4792,4449,2787,4080,3003,4245,3879,2493,7961,2574,9241
4,"Corée, République de",3469,3694,2720,2204,2485,3334,2561,1412,1415,2158,7163